### ISSUE TITLE
QA Test

### ISSUE THREAD

**Issue by stlutz** [hpi-swa-teaching/SWT18-Project-06#18]
I just completed all lectures and it looks great :) . I was unable to find any errors, even when going out of my way to try and break things. I did have some **minor** issues though (some of them probably not even worthy of being addressed):

  - [ ] The tutorial world looks exactly the same as the "real" world. Not really a problem, but at first I thought my window had a hole in it ^^ .
  - [x] The first time I switched between the current lesson and a previous one (to copy part of a previous solution), I unexpectedly lost all progress for the new, still incorrect one - even though I saved.
  - [x] There are a lot of suggested solutions that do not follow any style guidelines (that I can identify).
  - [x] I also noticed a few typos in the descriptions, especially the later ones.
  - [x] From chapter 5 onwards, there were no cool links to bring me directly to a discussed class or method anymore.
  - [x] [Chapter 2 - "Load an Image"] The solution does not show how the user was expected to solve the lesson.
  - [x] [Chapter 6 - "Rotation Basics"] There is very little guidance here (in comparision to previous lessons). I had no clue what was really expected of me and basically had to cheat to solve it.
  - [x] [Chapter 6 - "Rotate Morph by Angle"] Again, there was very little help here. I tried to add another TransformationMorph around the given Morph, not realizing that my owner already was one. Also: I was unable to see the resulting Morph.

**Comment by Jeilef** [comment]
I am working on the save when switching between lectures
EDIT: done
